version: 0.2
env:
  variables:
    # 改成你自己的ECR地址
    ECR_REPOSITORY_URI: 123456789012.dkr.ecr.ap-southeast-1.amazonaws.com/my-demo-service
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH}
  build:
    commands:
      - echo Build started on `date`
      - docker build -t $ECR_REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Pushing Docker image to ECR
      - docker push $ECR_REPOSITORY_URI:$IMAGE_TAG
artifacts:
  files: []
cache:
  paths:
    - /root/.docker/**/*
